# Generated by Django 5.0.4 on 2024-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_header_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
